### ISSUE TITLE
'Disabled' class

### ISSUE THREAD

**Issue by jonlambert** [th0ran/richard_ii#2]
Hi guys.

As you know, there will be two modes for the form... "Disabled" and "Enabled". Although my code will dynamically apply the `disabled=disabled` parameter to the form, I will also add the classes: `disabled` and `enabled` respectively to the `<form>` element. If you guys want to style the form in some way to give some reaction it would be awesome! Perhaps a greyed out submit button with a message?

**Comment by th0ran** [comment]
I think it would be enough if it just went transparent and not clickable.

**Comment by selcukcura** [comment]
Great! Styling it shouldn't be a problem

**Comment by jonlambert** [comment]
Cheers guys :smile: I've just finished the initial implementation... question submission and disabling now works. I'll tidy things up and make a pull request.

**Comment by th0ran** [comment]
Cool! Can´t wait to see how it works.

**Comment by cyberwest** [comment]
Thanks, Jon!

Dr James Morris,
Subject Leader, Web Media
Ravensbourne
Penrose Way
London SE10 0EW

T: +44 (0) 20 3040 3819
M: +44 (0) 7787 124014
@RaveWebMedia

**Comment by selcukcura** [comment]
Nice work Jon!
