### ISSUE TITLE
Overwriting of FTP site...

### ISSUE THREAD

**Issue by jonlambert** [th0ran/richard_ii#4]
Hi guys,

I uploaded all the files and configured the database etc. but it seems someone has overwritten my changes. If I now re-upload my bits it will undo whoever uploaded stuff's work.

It's imperative this doesn't happen during production as we risk breaking or corrupting the database!

Cheers,
Jon

**Comment by selcukcura** [comment]
Hi Jon, 

I noticed a typo on 'shedule' and changed it to schedule. That must've broken it.

My mistake!
